### PR TITLE
Updated clevis install for RHEL9

### PR DESCRIPTION
**Pull request by tscully**
Script is failing on RHEL 9 systems as specific python version does not exist.

Added condition to only try installing specific python version on RHEL 8.

Also added a space in the GDM config section, was throwing a non fatal error.

### CODE REVIEW

**Review by jhodrien — COMMENTED** [review]
Why not just use python3 on both?

**Comment by tscully** [comment]
I'd be happy to just use 'python3'.

I just made it conditional as I didn't have any history as to why it was specifically python36 on RHEL8, and didn't have a test machine to build I could verify RHEL8 on.

**Comment by jhodrien** [comment]
I can't answer that one.  If there's some reason we're scared of python3 due to something else sneaking in the PATH somehow, could use /usr/libexec/platform-python on both?

**Comment by tscully** [comment]
I'd be happy with that.  I don't actually see how trying to install python3 here relates to what wer're doing with clevis, was just really being cautious about changing something I didn't understand or was able to completely test.  

I can revert to simply installing the clevis packages, and push that.

**Comment by tscully** [comment]
Changed to just use 'python3' for all OS revs.

**Review by issjwh — APPROVED** [review]

**Pull request merged**
